server:
  port: 8088

girl:
  cupSize: B
  age: 24
  content: "cupSize: ${cupSize}, age: ${age}"


spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5